sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - prager.adam87@gmail.com
